trial/leavemgt/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, HiddenField, StringField


class LeaveAction(FlaskForm):

    approve = HiddenField('approve')
    cancel = HiddenField('cancel')
    reject = HiddenField('reject')
    id = HiddenField('')
    confirm = SubmitField('Confirm')

trial/leavemgt/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from trial import db
from flask_login import login_required, current_user
from trial.models import Leave, User, Staff, EmployeeDetails
from trial.users.utils import admin_required
from trial.leavemgt.forms import LeaveAction
from datetime import date, datetime


leavemgt = Blueprint('leavemgt', __name__)

@leavemgt.route('/management_dashboard', methods=['GET'])
@admin_required
@login_required
def leave_dash():
    form = LeaveAction()
    all_req = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count() 
    pending_no = Leave.query.filter_by(leave_status="Pending").count()
    
    tot_req = rej_no + app_no + pending_no
    return render_template('leavemgt/leave_mgt_dash.html', all_req=all_req, form=form, 
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no, tot_req=tot_req)

@leavemgt.route('/act_on_leave/<int:leave_id>', methods=['GET', 'POST'])
@login_required
def decide_on_leave_req(leave_id):
    form = LeaveAction()
    req = Leave.query.get_or_404(leave_id)
    if form.validate_on_submit():
        if form.approve.data:
            req.leave_status = form.approve.data
            req.reasons = request.form.get('newvals')
            print(request.form.get('newvals'))
        elif form.reject.data:
            req.leave_status = form.reject.data
            req.reasons = request.form.get('rejval')
            print(request.form.get('rejval'))
            
        db.session.commit()
    return redirect(url_for('leavemgt.leave_dash')) 

#View Cancelled Requests
@leavemgt.route("/view_cancelled/requests", methods=['GET', 'POST'])
@login_required
def cancelled_req():
    form = LeaveAction()
    cancelled = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()

    tot_req = rej_no + app_no + pending_no
    return render_template('leavemgt/cancelled_req.html', form=form, cancelled=cancelled, rej_no=rej_no, 
                            cancel_no=cancel_no, app_no=app_no, pending_no=pending_no,  tot_req=tot_req)

#View Rejected Requests
@leavemgt.route("/view_rejected/requests", methods=['GET', 'POST'])
@login_required
def rejected_req():
    form = LeaveAction()
    rejected = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()

    tot_req = rej_no + app_no + pending_no
    return render_template('leavemgt/rejected_req.html', form=form, rejected=rejected,
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no, tot_req=tot_req)

#View Approved Requests
@leavemgt.route("/view_approved/requests", methods=['GET', 'POST'])
@login_required
def approved_req():
    form = LeaveAction() 
    approved = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()

    tot_req = rej_no + app_no + pending_no
    return render_template('leavemgt/approved_req.html', form=form, approved=approved,
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no, tot_req=tot_req)

#View Pending Requests
@leavemgt.route("/view_pending/requests", methods=['GET', 'POST'])
@login_required
def pending_req():
    form = LeaveAction()
    pending = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()

    tot_req = rej_no + app_no + pending_no
    return render_template('leavemgt/pending_req.html', form=form, pending=pending,
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no, tot_req=tot_req) 



#View Pending Requests
@leavemgt.route("/view_staff_list", methods=['GET', 'POST']) 
@login_required
def view_staff():
    form = LeaveAction()
    pending = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()
    staff_pers = EmployeeDetails.query.all()
    today = date.today()
    
    tot_req = rej_no + app_no + pending_no
    return render_template('admin/emp_details_list.html', form=form, pending=pending,rej_no=rej_no, cancel_no=cancel_no, 
                            app_no=app_no, pending_no=pending_no, tot_req=tot_req, staff_pers=staff_pers, 
                            today=today, datetime=datetime)

#View Pending Requests
@leavemgt.route("/update_staff_list", methods=['GET', 'POST']) 
@login_required
def staff_list_update():
    form = LeaveAction()
    pending = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()
    staff_pers = EmployeeDetails.query.all()
   
    
    tot_req = rej_no + app_no + pending_no
    return render_template('admin/employee_list.html', form=form, pending=pending,rej_no=rej_no, cancel_no=cancel_no, 
                            app_no=app_no, pending_no=pending_no, tot_req=tot_req, staff_pers=staff_pers) 

    

    
    

trial/templates/leavemgt/approved_req.html
{% extends "leavemgt/leavedash_layout.html" %}
{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Dashboard</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Dashboard</li>  
            </ol>
            {% include "leavemgt/leave_dash_menus.html" %}
            
            <!--<div class="row">
                <div class="col-xl-6">
                    <div class="card mb-4">
                        <div class="card-header"> 
                            <i class="fas fa-chart-area mr-1"></i>
                            Area Chart Example
                        </div>
                        <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                    </div>
                </div>
            </div>-->
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Approved Leave Requests
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Section</th>
                                    <th>Reason</th>
                                    <th>Leave From/To</th>
                                    <th>Status</th>
                                    <th>Details</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for requests in approved %}
                                {% if requests.leave_status == "Approved" %}
                                <tr>
                                    <td>{{ requests.name }}</td>
                                    <td>{{ requests.email }}</td>
                                    <td>{{ requests.section }}</td> 
                                    <td>{{ requests.supp_info }}</td>
                                    <td>{{ requests.start_date }} to {{ requests.end_date }}</td>
                                    <td>
                                        <span class="btn btn-success btn-sm">{{ requests.leave_status }}</span>
                                    </td>
                                    <td style="text-align: center;">
                                        <a href="#user-{{loop.index}}-details"><i class="fa fa-info-circle" data-toggle="modal" data-target="#modal_{{ requests.id }}"></i></a>
                                        <div class="modal fade" id="modal_{{ requests.id }}" tabindex="-1" role="dialog" aria-labelledby="label_modal_{{ requests.id }}" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                <div class="modal-header text-center">
                                                  <h5 class="modal-title" id="label_modal_{{ requests.id }}">
                                                    {{ requests.name }}'s leave request
                                                  </h5>
                                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                  </button>
                                                </div>
                                                <div class="modal_approval_choice modal-body pb-0">
                                                  <div class="row"><div class="col"><strong>Reasons</strong></div></div>
                                                  <div class="row">
                                                    <div class="col pt-3 border-top border-right">No comments</div>
                                                    <div class="col-xl-6 col-sm-6 col-xs-6">
                                                      <div class="row">
                                                        <div class="col-xl-12 col-sm-12 col-xs-12 pt-3 mb-3 pb-3 border-top border-bottom text-center">
                                                          <p class="text-success">Already Approved!</p>
                                                        </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                    </td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

trial/templates/leavemgt/leave_dash_menus.html
<div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">Approved Requests
                <span class="badge badge-pill badge-light ml-3">
                    {{ app_no }}
                </span>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{{ url_for('leavemgt.approved_req') }}"> 
                    View Details
                </a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body">New Requests
                <span class="badge badge-pill badge-light ml-3">
                    {{ pending_no }}
                </span>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{{ url_for('leavemgt.pending_req') }}">
                    View Details
                </a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body">All Requests
                <span class="badge badge-pill badge-light ml-3"> 
                    {{ tot_req }}
                </span>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{{ url_for('leavemgt.leave_dash') }}">
                    View Details
                </a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body">Rejected Requests
                <span class="badge badge-pill badge-light ml-3">
                    {{ rej_no}}
                </span>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{{ url_for('leavemgt.rejected_req') }}">
                    View Details
                </a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    {% if not current_user.role_id == 3 %}
    <div class="col-xl-3 col-md-6">
        <div class="card bg-secondary text-white mb-4">
            <div class="card-body">Cancelled Requests
                <span class="badge badge-pill badge-light ml-3"> 
                    {{ cancel_no }}
                </span>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" href="{{ url_for('leavemgt.cancelled_req') }}">
                    View Details
                </a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    {% endif %}
</div>

trial/templates/leavemgt/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Page Title - SB Admin</title>
        <link href="css/styles.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                    <div class="card-body">
                                        <form>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputEmailAddress">Email</label>
                                                <input class="form-control py-4" id="inputEmailAddress" type="email" placeholder="Enter email address" />
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputPassword">Password</label>
                                                <input class="form-control py-4" id="inputPassword" type="password" placeholder="Enter password" />
                                            </div>
                                            <div class="form-group">
                                                <div class="custom-control custom-checkbox">
                                                    <input class="custom-control-input" id="rememberPasswordCheck" type="checkbox" />
                                                    <label class="custom-control-label" for="rememberPasswordCheck">Remember password</label>
                                                </div>
                                            </div>
                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <a class="small" href="password.html">Forgot Password?</a>
                                                <a class="btn btn-primary" href="index.html">Login</a>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

trial/templates/leavemgt/pending_req.html
{% extends "leavemgt/leavedash_layout.html" %}
{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Dashboard</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
            {% include "leavemgt/leave_dash_menus.html" %}
            
            <!--<div class="row">
                <div class="col-xl-6">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-chart-area mr-1"></i>
                            Area Chart Example
                        </div>
                        <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                    </div>
                </div>
            </div>-->
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Leave Requests on Pending
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Section</th>
                                    <th>Reason</th>
                                    <th>Leave From/To</th>
                                    <th>Status</th>
                                    <th>Details</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for requests in pending %}
                                {% if requests.leave_status == "Pending" %}
                                <tr>
                                    <td>{{ requests.name }}</td>
                                    <td>{{ requests.email }}</td>
                                    <td>{{ requests.section }}</td>
                                    <td>{{ requests.supp_info }}</td>
                                    <td>{{ requests.start_date }} to {{ requests.end_date }}</td>
                                    <td>
                                        <span class="btn btn-warning btn-sm">{{ requests.leave_status }}</span>
                                    </td>
                                    <td style="text-align: center;">
                                        <a href="#user-{{loop.index}}-details"><i class="fa fa-info-circle" data-toggle="modal" data-target="#modal_{{ requests.id }}"></i></a>
                                        <div class="modal fade" id="modal_{{ requests.id }}" tabindex="-1" role="dialog" aria-labelledby="label_modal_{{ requests.id }}" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                <div class="modal-header text-center">
                                                  <h5 class="modal-title" id="label_modal_{{ requests.id }}">
                                                    {{ requests.name }}'s leave request
                                                  </h5>
                                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                  </button>
                                                </div>
                                                <div class="modal_approval_choice modal-body pb-0">
                                                  <div class="row"><div class="col"><strong>Reasons</strong></div></div>
                                                  <div class="row">
                                                    <div class="col pt-3 border-top border-right">
                                                        {{ requests.supp_info }}
                                                    </div>
                                                    <div class="col-xl-6 col-sm-6 col-xs-6">
                                                      <div class="row">
                                                        <!--
                                                        <div class="col-xl-12 col-sm-12 col-xs-12 pt-3 mb-3 pb-3 border-top border-bottom text-center">
                                                          <p class="text-success">Already Approved!</p>
                                                        </div>
                                                        
                                                        <div class="col-xl-12 col-sm-12 col-xs-12 pt-3 mb-3 pb-3 border-top border-bottom text-center">
                                                          <p>This Leave Request has been <em class="text-danger">rejected.</em></p>
                                                          <p>see comments</p>
                                                        </div>
                                                        
                                                        <div class="col-xl-12 col-sm-12 col-xs-12 pt-3 mb-3 pb-3 border-top border-bottom text-center">
                                                          <p>This Leave Request has been <em class="text-warning">cancelled..</em></p>
                                                        </div>-->
                                                        
                                                          <div class="col-xl-12 col-sm-12 col-xs-12 pt-2 mb-2 pb-2 border-top border-bottom">
                                                            <button type="button" class="approve btn btn-success" value="approved">Approve</button> 
                                                          </div>
                                                          <div class="col-xl-12 col-sm-12 col-xs-12 mb-2 pb-2 border-bottom">
                                                              <button type="button" class="reject btn btn-danger" value="rejected">Reject</button>
                                                          </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                                <!-- Approve Request Form -->
                                                <form class="approval_modal_form" action="{{ url_for('leavemgt.decide_on_leave_req', leave_id=requests.id) }}" method="POST">
                                                    {{ form.csrf_token }}
                                                  <div class="confirmation modal-body pb-0">
                                                    <p>Please confirm your selection</p>
                                                    <input name="user_id" class="d-none" type="text" value="{{request._id}}">
                                                      {{ form.approve(value="Approved")}}   
                                                  </div>
                                                  <div class="confirmation modal-footer justify-content-center">
                                                      <button type="button" class="btn btn-secondary"  data-dismiss="modal">Close</button>
                                                      <button type="button" class="modal_back_to_choice btn btn-secondary">Back</button>
                                                      {{ form.confirm( class="btn btn-primary") }}  
                                                  </div> 
                                                </form>
                                                <!--Cancel Request Form-->
                                                <form class="approval_modal_form" action="{{ url_for('leavemgt.decide_on_leave_req', leave_id=requests.id) }}" method="POST">
                                                    {{ form.csrf_token }}
                                                  <div class="cancel_confirmation modal-body pb-0">
                                                    <p>Please confirm your selection</p>
                                                    <input name="user_id" class="d-none" type="text" value="{{request._id}}">
                                                      {{ form.cancel(value="Cancelled")}}   
                                                  </div>
                                                  <div class="cancel_confirmation modal-footer justify-content-center">
                                                      <button type="button" class="btn btn-secondary"  data-dismiss="modal">Close</button>
                                                      <button type="button" class="modal_back_to_choice btn btn-secondary">Back</button>
                                                      {{ form.confirm( class="btn btn-primary") }}  
                                                  </div> 
                                                </form>

                                                <!--Reject Request Form-->
                                                <form class="approval_modal_form" action="{{ url_for('leavemgt.decide_on_leave_req', leave_id=requests.id) }}" method="POST">
                                                    {{ form.csrf_token }}
                                                  <div class="reject_confirmation modal-body pb-0">
                                                    <p>Please confirm your selection</p>
                                                    <input name="user_id" class="d-none" type="text" value="{{request._id}}">
                                                      {{ form.reject(value="Rejected")}}   
                                                  </div>
                                                  <div class="reject_confirmation modal-footer justify-content-center">
                                                      <button type="button" class="btn btn-secondary"  data-dismiss="modal">Close</button>
                                                      <button type="button" class="modal_back_to_choice btn btn-secondary">Back</button>
                                                      {{ form.confirm( class="btn btn-primary") }}  
                                                  </div> 
                                                </form>
                                              </div>
                                            </div>
                                          </div>
                                    </td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}