trial/leavemgt/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from trial import db
from flask_login import login_required, current_user
from trial.models import Leave, User, Staff, EmployeeDetails
from trial.users.utils import admin_required
from trial.leavemgt.forms import LeaveAction
from datetime import date, datetime


leavemgt = Blueprint('leavemgt', __name__)

@leavemgt.route('/management_dashboard', methods=['GET'])
@admin_required
@login_required
def leave_dash():
    form = LeaveAction()
    all_req = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count() 
    pending_no = Leave.query.filter_by(leave_status="Pending").count()
    
    tot_req = rej_no + app_no + pending_no
    return render_template('leavemgt/leave_mgt_dash.html', all_req=all_req, form=form, 
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no, tot_req=tot_req)

@leavemgt.route('/act_on_leave/<int:leave_id>', methods=['GET', 'POST'])
@login_required
def decide_on_leave_req(leave_id):
    form = LeaveAction()
    req = Leave.query.get_or_404(leave_id)
    if form.validate_on_submit():
        if form.approve.data:
            req.leave_status = form.approve.data
            req.reasons = request.form.get('newvals')
            print(request.form.get('newvals'))
        elif form.reject.data:
            req.leave_status = form.reject.data
            req.reasons = request.form.get('rejval')
            print(request.form.get('rejval'))
            
        db.session.commit()
    return redirect(url_for('leavemgt.leave_dash')) 

#View Cancelled Requests
@leavemgt.route("/view_cancelled/requests", methods=['GET', 'POST'])
@login_required
def cancelled_req():
    form = LeaveAction()
    cancelled = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()

    tot_req = rej_no + app_no + pending_no
    return render_template('leavemgt/cancelled_req.html', form=form, cancelled=cancelled, rej_no=rej_no, 
                            cancel_no=cancel_no, app_no=app_no, pending_no=pending_no,  tot_req=tot_req)

#View Rejected Requests
@leavemgt.route("/view_rejected/requests", methods=['GET', 'POST'])
@login_required
def rejected_req():
    form = LeaveAction()
    rejected = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()

    tot_req = rej_no + app_no + pending_no
    return render_template('leavemgt/rejected_req.html', form=form, rejected=rejected,
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no, tot_req=tot_req)

#View Approved Requests
@leavemgt.route("/view_approved/requests", methods=['GET', 'POST'])
@login_required
def approved_req():
    form = LeaveAction() 
    approved = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()

    tot_req = rej_no + app_no + pending_no
    return render_template('leavemgt/approved_req.html', form=form, approved=approved,
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no, tot_req=tot_req)

#View Pending Requests
@leavemgt.route("/view_pending/requests", methods=['GET', 'POST'])
@login_required
def pending_req():
    form = LeaveAction()
    pending = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()

    tot_req = rej_no + app_no + pending_no
    return render_template('leavemgt/pending_req.html', form=form, pending=pending,
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no, tot_req=tot_req) 



#View Pending Requests
@leavemgt.route("/view_staff_list", methods=['GET', 'POST']) 
@login_required
def view_staff():
    form = LeaveAction()
    pending = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()
    staff_pers = EmployeeDetails.query.all()
    today = date.today()
    
    tot_req = rej_no + app_no + pending_no
    return render_template('admin/emp_details_list.html', form=form, pending=pending,rej_no=rej_no, cancel_no=cancel_no, 
                            app_no=app_no, pending_no=pending_no, tot_req=tot_req, staff_pers=staff_pers, 
                            today=today, datetime=datetime)

#View Pending Requests
@leavemgt.route("/update_staff_list", methods=['GET', 'POST']) 
@login_required
def staff_list_update():
    form = LeaveAction()
    pending = Leave.query.all()
    rej_no = Leave.query.filter_by(leave_status="Rejected").count()
    app_no = Leave.query.filter_by(leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(leave_status="Pending").count()
    staff_pers = EmployeeDetails.query.all()
   
    
    tot_req = rej_no + app_no + pending_no
    return render_template('admin/employee_list.html', form=form, pending=pending,rej_no=rej_no, cancel_no=cancel_no, 
                            app_no=app_no, pending_no=pending_no, tot_req=tot_req, staff_pers=staff_pers) 

    

    
    

trial/users/routes.py
from flask import render_template, redirect, url_for, flash, request, Blueprint
from werkzeug.urls import url_parse
from flask_login import current_user, logout_user, login_required, login_user
from trial import db, bcrypt 
from trial.users.forms import RequestResetForm, ResetPasswordForm, LoginForm, UpdateAccountForm 
from trial.users.utils import send_reset_email, save_picture
from trial.models import User, Post, Leave
from trial.staff_list import update_staff, staff 
from trial.leavemgt.forms import LeaveAction

users = Blueprint('users', __name__) 


#Route for Login 
@users.route('/login', methods=['GET', 'POST']) 
def login():
    if current_user.is_authenticated:
        if current_user.role_id==1:
            return redirect(url_for('users.user_dashboard',user_name=current_user.name)) 
        elif current_user.role_id==3:
            return redirect(url_for('leavemgt.leave_dash'))
    form = LoginForm()
    if form.validate_on_submit():
        #Get User from Database
        user = User.query.filter_by(acc_gen_no=form.acc_gen.data).first() or User.query.filter_by(email=form.acc_gen.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data): 
            login_user(user, remember=form.remember.data)
            
            #Get the next parameter(if it exists redirect the user the requested page)
            next_page = request.args.get('next')
            if not next_page or url_parse(next_page).netloc != '':
                if current_user.role_id==1:
                    next_page = url_for('users.user_dashboard',user_name=current_user.name)
                elif current_user.role_id==3:
                    next_page = url_for('leavemgt.leave_dash')
            return redirect(next_page)

        else:
            flash('Unsuccessful Login. Please check email and password again', 'danger') 
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('landing/user_login.html', title='Login', form=form) 

#route for account template
@users.route('/account', methods=['GET', 'POST']) 
@login_required
def account(): 
    form = UpdateAccountForm()
    if form.validate_on_submit(): 
        #Check if there is a picture data
        if form.picture.data:
            #Set the user profile picture 
            picture_file = save_picture(form.picture.data)  
            current_user.image_file = picture_file
        #Set Updated details in the database 
        current_user.acc_gen_no = form.acc_gen.data
        current_user.email = form.email.data
        db.session.commit() 
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    #Populate fields with data from the database
    elif request.method == 'GET':
        form.acc_gen.data = current_user.acc_gen_no
        form.email.data = current_user.email
        form.dob.data = current_user.dob

    return render_template('users/account.html', title='Account', form=form)


#Route for logout
@users.route('/logout')
def logout():
    logout_user() 
    return redirect(url_for('main.home'))

@users.route('/add_staff_list')
def add_staff_list():
    update_staff(staff)
    return redirect(url_for('admin.dashboard'))

#Route to request reset Password(Where Email is entered to reset password) 
@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first() 
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    
    return render_template('landing/reset_request.html', form=form)

#Route for Reset Password
@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token) 
    if user is None:
        flash('Token is invalid or expired', 'warning')
        return redirect(url_for('users.reset_request')) 
    form = ResetPasswordForm()
    if form.validate_on_submit():
        #Hash Password
        hashed_pswd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        #Edit the password in the database
        user.password = hashed_pswd
        db.session.commit()
        flash('Password has been updated successfully!. You can now log in', 'success')
        return redirect(url_for('users.login'))
    
    return render_template('landing/reset_token.html', title='Reset Password', form=form)  

#Route to view user dashboard
@users.route('/user_dashboard/<string:user_name>', methods=['GET', 'POST'])
@login_required
def user_dashboard(user_name):
    form = LeaveAction()

    all_req = Leave.query.filter_by(name=user_name)
    total_req = Leave.query.filter_by(name=user_name).count()
    rej_no = Leave.query.filter_by(name=user_name, leave_status="Rejected").count()     
    app_no = Leave.query.filter_by(name=user_name, leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(name=user_name, leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(name=user_name, leave_status="Pending").count()

    return render_template('users/user_leave_dash.html', all_req=all_req, form=form,total_req = total_req, 
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no)


@users.route('/decide_on_leave_req/<int:leave_id>', methods=['GET', 'POST'])
@login_required
def act_on_leave_req(leave_id):
    form = LeaveAction()
    req = Leave.query.get_or_404(leave_id)
    if form.validate_on_submit():
        if form.cancel.data:
            req.leave_status = form.cancel.data
        db.session.commit()
    return redirect(url_for('users.user_dashboard',user_name=current_user.name))

#Route to view user's pending requests
@users.route('/user_leave_request/<string:username>/pending_requests', methods=['GET', 'POST'])
def user_pending_req(username):
    form = LeaveAction()
    pending = Leave.query.filter_by(name=username)
    total_req = Leave.query.filter_by(name=username).count()
    rej_no = Leave.query.filter_by(name=username, leave_status="Rejected").count()
    app_no = Leave.query.filter_by(name=username, leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(name=username, leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(name=username, leave_status="Pending").count()
    return render_template('users/user_pending.html', form=form, pending=pending,total_req = total_req,
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no,
                            title="Pending Requests")

#Route to view user's rejected requests
@users.route('/user_leave_request/<string:username>/rejected_requests', methods=['GET', 'POST'])
def user_rejected_req(username):
    form = LeaveAction()
    rejected = Leave.query.filter_by(name=username)
    total_req = Leave.query.filter_by(name=username).count()
    rej_no = Leave.query.filter_by(name=username, leave_status="Rejected").count()
    app_no = Leave.query.filter_by(name=username, leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(name=username, leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(name=username, leave_status="Pending").count()
    return render_template('users/user_rejected.html', form=form, rejected=rejected, total_req = total_req,
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no, 
                            title="Rejected Requests")

#Route to view user's cancelled requests
@users.route('/user_leave_request/<string:username>/cancelled_requests', methods=['GET', 'POST'])
def user_cancelled_req(username):
    form = LeaveAction()
    cancelled = Leave.query.filter_by(name=username)
    total_req = Leave.query.filter_by(name=username).count()
    rej_no = Leave.query.filter_by(name=username, leave_status="Rejected").count()
    app_no = Leave.query.filter_by(name=username, leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(name=username, leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(name=username, leave_status="Pending").count()
    return render_template('users/user_cancelled.html', form=form, cancelled=cancelled, total_req = total_req,
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no,
                            title="Cancelled Requests")

#Route to view user's approved requests
@users.route('/user_leave_request/<string:username>/approved_requests', methods=['GET', 'POST'])
def user_approved_req(username):
    form = LeaveAction()
    approved = Leave.query.filter_by(name=username)
    total_req = Leave.query.filter_by(name=username).count()
    rej_no = Leave.query.filter_by(name=username, leave_status="Rejected").count()
    app_no = Leave.query.filter_by(name=username, leave_status="Approved").count()
    cancel_no = Leave.query.filter_by(name=username, leave_status="Cancelled").count()
    pending_no = Leave.query.filter_by(name=username, leave_status="Pending").count()
    return render_template('users/user_approved.html', form=form, approved=approved, total_req = total_req,
                            rej_no=rej_no, cancel_no=cancel_no, app_no=app_no, pending_no=pending_no,
                            title="Approved Requests")

trial/templates/users/reset_request.html
{% extends "includes/layout.html" %}
{% block content %}
<div class="container">
    <div class="row blog_details_inner" style="margin-left: 4%;">
        <div class="col-md-8"  style="margin-top: 2px;">
            <div class="modal_th" style="height: 570px;">
                <form action="" method="POST" enctype="multipart/form-data">
                    <div class="loginwrap" style="margin-top: 4%;">
                            <legend>RESET PASSWORD</legend>
                        <div class="form-group">
                            {{ form.email.label }}

                            <!--If form had errors-->
                            {% if form.email.errors %}
                                {{ form.email(class="form-control", style="border-color: #a94442;") }}
                                <div class="form-group has-error">
                                    {% for error in form.email.errors %}
                                        <span class="help-block">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            <!--if there are no errors-->
                            {% else %}
                                {{ form.email(class="form-control")}} 
                            {% endif %}
                        </div><br>
                        <div class="form-group">
                            {{ form.submit(class="btn submit_btn form-control", style="color: #494848;") }} <br>
                        </div>     
                    </div> 
                    {{ form.csrf_token }} 
                </form>
            </div> 
        </div>
        {% include "includes/sidebar.html" %} 
    </div>
</div>
{% endblock content %}

trial/templates/users/user_leave_dash.html
{% extends "users/users_dash_layout.html" %}
{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Dashboard</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Dashboard/All Requests</li>
            </ol>
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-success text-white mb-4">
                        <div class="card-body">Approved Requests
                            <span class="badge badge-pill badge-light ml-3">
                                {{ app_no }}
                            </span>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" 
                                href="{{ url_for('users.user_approved_req', username=current_user.name) }}">
                                View Details
                            </a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-warning text-white mb-4">
                        <div class="card-body">New Requests
                            <span class="badge badge-pill badge-light ml-3">
                                {{ pending_no }}
                            </span>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" 
                            href="{{ url_for('users.user_pending_req', username=current_user.name) }}">
                                View Details
                            </a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-primary text-white mb-4">
                        <div class="card-body">All Requests
                            <span class="badge badge-pill badge-light ml-3">
                                {{ total_req }}
                            </span>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" 
                                href="{{ url_for('users.user_dashboard', user_name=current_user.name) }}">
                                View Details
                            </a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-danger text-white mb-4">
                        <div class="card-body">Rejected Requests
                            <span class="badge badge-pill badge-light ml-3">
                                {{ rej_no }}
                            </span>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" 
                                href="{{ url_for('users.user_rejected_req', username=current_user.name) }}">
                                View Details
                            </a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-secondary text-white mb-4">
                        <div class="card-body">Cancelled Requests
                            <span class="badge badge-pill badge-light ml-3">
                                {{ cancel_no }}
                            </span>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" 
                                href="{{ url_for('users.user_cancelled_req', username=current_user.name) }}">
                                View Details
                            </a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!--<div class="row">
                <div class="col-xl-6">
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-chart-area mr-1"></i>
                            Area Chart Example
                        </div>
                        <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                    </div>
                </div>
            </div>-->
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Leave Requests
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Section</th>
                                    <th>Reason</th>
                                    <th>Leave From/To</th>
                                    <th>Status</th>
                                    <th>Details</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for requests in all_req %}
                                <tr>
                                    <td>{{ requests.name }}</td> 
                                    <td>{{ requests.email }}</td>
                                    <td>{{ requests.section }}</td>
                                    <td>{{ requests.supp_info }}</td>
                                    <td>{{ requests.start_date }} to {{ requests.end_date }}</td>
                                    <td>
                                        {% if requests.leave_status == "Approved" %}
                                        <span class="btn btn-success btn-sm">{{ requests.leave_status }}</span>
                                        {% elif requests.leave_status == "Pending" %}
                                        <span class="btn btn-warning btn-sm">{{ requests.leave_status }}</span>
                                        {% elif requests.leave_status == "Cancelled" %}
                                        <span class="btn btn-secondary btn-sm">{{ requests.leave_status }}</span>
                                        {% elif requests.leave_status == "Rejected" %}
                                        <span class="btn btn-danger btn-sm">{{ requests.leave_status }}</span> 
                                        {% endif %}
                                    </td>
                                    <td style="text-align: center;">
                                        <a href="#user-{{loop.index}}-details"><i class="fa fa-info-circle" data-toggle="modal" data-target="#modal_{{ requests.id }}"></i></a>
                                        <div class="modal fade" id="modal_{{ requests.id }}" tabindex="-1" role="dialog" aria-labelledby="label_modal_{{ requests.id }}" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                <div class="modal-header text-center">
                                                  <h5 class="modal-title" id="label_modal_{{ requests.id }}">
                                                    {{ requests.name }}'s leave request
                                                  </h5>
                                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                  </button>
                                                </div>
                                                <div class="modal_approval_choice modal-body pb-0"> 
                                                  <div class="row"><div class="col"><strong>Reasons</strong></div></div>
                                                  <div class="row">
                                                    <div class="col pt-3 border-top border-right">
                                                        {{ requests.supp_info }}
                                                    </div>
                                                    <div class="col-xl-6 col-sm-6 col-xs-6"> 
                                                      <div class="row">
                                                        {% if requests.leave_status=="Approved" %}
                                                        <div class="col-xl-12 col-sm-12 col-xs-12 pt-3 mb-3 pb-3 border-top border-bottom text-center">
                                                          <p class="text-success">Already Approved!</p>
                                                        </div>
                                                        {% elif requests.leave_status=="Rejected" %}
                                                        <div class="col-xl-12 col-sm-12 col-xs-12 pt-3 mb-3 pb-3 border-top border-bottom text-center">
                                                          <p>This Leave Request has been <em class="text-danger">rejected.</em></p>
                                                        </div>
                                                        {% elif requests.leave_status=="Cancelled" %}
                                                        <div class="col-xl-12 col-sm-12 col-xs-12 pt-3 mb-3 pb-3 border-top border-bottom text-center">
                                                          <p>This Leave Request has been <em class="text-warning">cancelled..</em></p>
                                                        </div>
                                                        {% else %}
                                                        <div class="col-xl-12 col-sm-12 col-xs-12 pb-2 pt-2 mb-2 pb-2 border-top border-bottom">
                                                            <button type="button" class="delete btn btn-secondary" value="deleted">Cancel</button>
                                                        </div>
                                                        {% endif %}
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                                <!--Cancel Request Form-->
                                                <form class="approval_modal_form" 
                                                    action="{{ url_for('users.act_on_leave_req', leave_id=requests.id) }}" method="POST">
                                                    {{ form.csrf_token }}
                                                  <div class="cancel_confirmation modal-body pb-0">
                                                    <p>Please confirm your selection</p>
                                                    <input name="user_id" class="d-none" type="text" value="{{request._id}}">
                                                      {{ form.cancel(value="Cancelled")}}   
                                                  </div>
                                                  <div class="cancel_confirmation modal-footer justify-content-center">
                                                      <button type="button" class="btn btn-secondary"  data-dismiss="modal">Close</button>
                                                      <button type="button" class="modal_back_to_choice btn btn-secondary">Back</button>
                                                      {{ form.confirm( class="btn btn-primary") }}  
                                                  </div> 
                                                </form>

                                              </div>
                                            </div>
                                          </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>  
{% endblock content %}