trial/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class SearchForm(FlaskForm):
    q = StringField('Search', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

trial/generalforms/routes.py
from flask import render_template, redirect, url_for, flash, send_file, make_response, Blueprint, request
from flask_login import current_user
import flask_login
from flask_login.utils import login_required
from trial import db
from trial.generalforms.forms import DefectReportForm, LeaveForm
from trial.models import Leave, Post 
import pdfkit


generalforms = Blueprint('generalforms', __name__) 
 

#Create a route for defect form
@generalforms.route('/defect', methods=['GET', 'POST'])
def defect():
    form = DefectReportForm()
    if form.validate_on_submit():
        flash(f'Defect Report Form submitted successfully', 'success') 
        return redirect(url_for('generalforms.defect'))
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('generalforms/defect_rep.html', title='Road Defects Report', form=form, posts=posts)

#Create a route for leave Form    
@generalforms.route('/leave', methods=['GET', 'POST']) 
@login_required
def leave():
    form = LeaveForm()
    if form.validate_on_submit():
        name=request.form.get('name')
        le_ave = Leave(name=name, rank=form.rank.data, section=form.section.data, date_app=form.date_app.data,
                    tele_no=form.tele_no.data, leave_cat=form.leave_cat.data, no_of_days=form.no_of_days.data, 
                    start_date=form.start_date.data, end_date=form.end_date.data, supp_info=form.supp_info.data,
                    address=form.address.data, mobile_no=form.mobile_no.data, email=form.email.data, 
                    days_proceed=form.days_proceed.data, effec_date=form.effec_date.data, resump_date=form.resump_date.data,
                    outs_days=form.outs_days.data, leave_status=form.leavestatus.data, author=current_user)
        db.session.add(le_ave)
        db.session.commit()
        flash(f"Leave form submitted successfully", 'success')
        return redirect(url_for('generalforms.view_form', post_id=le_ave.id))
    posts = Post.query.order_by(Post.id.desc()).all() 
    return render_template('generalforms/leave_form.html', title='Leave Form Report', form=form, posts=posts)



#Route to view the Leave form
@generalforms.route('/post/<int:post_id>') 
@login_required
def post(post_id):
    post = Leave.query.get_or_404(post_id)
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('generalforms/render_form.html', post=post, posts=posts) 

#Route for View form 
@generalforms.route('/view_form/<int:post_id>', methods=['GET', 'POST']) 
@login_required
def view_form(post_id):
    post = Leave.query.get_or_404(post_id)
    posts = Post.query.order_by(Post.id.desc()).all()
    
    return render_template('generalforms/view_lv_form.html', title='Leave', post=post, posts=posts) 

#Generate pdf from the Leave Form
@generalforms.route('/get_pdf/<int:post_id>', methods=['GET','POST'])
@login_required
def get_pdf(post_id):

    post = Leave.query.get_or_404(post_id)
    posts = Post.query.order_by(Post.id.desc()).all()
    rendered= render_template('generalforms/render_form.html', title=current_user.name, post=post, posts=posts)
    css = ['trial/static/css/bootstrap.min.css', 'trial/static/css/style.css']

    options = {'enable-local-file-access': None}
    pdf = pdfkit.from_string(rendered, False, options=options, css=css)
    response = make_response(pdf)
    
    response.headers['content-Type'] = 'application/pdf'
    response.headers['content-Disposition'] = 'inline; filename=output.pdf'

    return response

#Render pdf format of the Leave Form
@generalforms.route('/render/<int:post_id>', methods=['GET', 'POST'])
def render(post_id):
    post = Leave.query.get_or_404(post_id)
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('generalforms/render_form.html', post=post, title=current_user.name, posts=posts)


#Route to view other forms   
@generalforms.route('/other_forms', methods=['GET', 'POST'])
@login_required
def others():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('generalforms/other_forms.html', title='Other Forms', posts=posts)

#Route to download Hospital Form
@generalforms.route('/download_hospital-form')
@login_required
def download_hosp():
    p = './static/other_forms/GHANA HIGHWAY AUTHORITY (HOSPITAL FORM).pdf'

    return send_file(p, as_attachment=True)

#Route to download Accomodation Form
@generalforms.route('/download_accomodation-form')
@login_required     
def download_accom():
    p = './static/other_forms/GHANA HIGHWAY AUTHORITY (REQUEST FOR ACCOMODATION).pdf'

    return send_file(p, as_attachment=True)

#Route to download Right to information pdf
@generalforms.route('/download_Right_to_Info')
#@login_required     
def download_Right_to_Info():
    p = './static/other_forms/Right to Information Act, 2019.pdf'

    return send_file(p, as_attachment=True)

#Route to download Right to information pdf
@generalforms.route('/download_RTI_MAN')
#@login_required     
def download_RTI_Man():
    p = './static/other_forms/RTI_Manual-Ghana Highway Authority 2023.pdf'

    return send_file(p, as_attachment=True)

#Route to download Classes and Types pdf
@generalforms.route('/download_RTI_Classes')
#@login_required     
def download_RTI_Classes():
    p = './static/other_forms/Classes and Types.pdf'

    return send_file(p, as_attachment=True)


#Route to download Classes and Types pdf
@generalforms.route('/download_application_form')
#@login_required     
def download_application_form():
    p = './static/other_forms/Online application Forms fillable.pdf'

    return send_file(p, as_attachment=True)

trial/main/routes.py
from flask import render_template, Blueprint, g, current_app, redirect, url_for, request, jsonify, flash
from trial import db, bcrypt
from werkzeug.urls import url_parse
from flask_login import current_user, login_user
from trial.main.forms import SearchForm
from trial.projects.forms import DateForm
from trial.models import CompletedProj, Post, Gallery, User
from trial.users.forms import RequestResetForm, ResetPasswordForm, LoginForm, UpdateAccountForm


main = Blueprint('main', __name__)

#Create route for home app
@main.route('/')
@main.route('/home')
def home(): 
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/home.html', posts=posts) 

#Create a route for divisions
@main.route('/divisions')
def division():
    posts = Post.query.order_by(Post.id.desc()).all() 
    return render_template('main/divisions.html', title='Division', posts=posts)

#Create a route for divisions
@main.route('/no_info')
def no_info():
    posts = Post.query.order_by(Post.id.desc()).all() 
    return render_template('main/no_info.html', title='No Info', posts=posts) 

#Create a route for Landing Page
@main.route('/main/landing_page')
def landing_page():    
    return render_template('landing/landing_page.html')


#Create a route for Yearly Report 
@main.route('/report/road_con_survey/')
def road_con_survey():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/road_con_survey.html', title='Road Con. Survey Report', posts=posts)

#Create a route for 2018 report 
@main.route('/yearly_report/2018')
def report_2018():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/report_2018.html', title='2018 Report', posts=posts)

#Create a route for 2019 report 
@main.route('/yearly_report/2019')
def report_2019():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/report_2019.html', title='2019 Report', posts=posts)

#Create a route for 2020 report 
@main.route('/report/proj_funding')
def proj_funding():
    posts = Post.query.order_by(Post.id.desc()).all() 
    return render_template('main/proj_funding.html', title='2020 Report', posts=posts)

@main.route('/institution_profile')
def inst_prof():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/institution_profile.html', title='Institution Profile', posts=posts)

@main.route('/ceo_office')
def ceo_office():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/ceo_office.html', title='Institution Profile', posts=posts)

@main.route('/road_net')
def road_net():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/road_network.html', title='Road Network', posts=posts)

@main.route('/photo_gallery')
def photo_gallery():
    posts = Post.query.order_by(Post.id.desc()).all()
    pics = Gallery.query.all()
    return render_template('main/photo-gallery.html', title='Gallery', posts=posts, pics=pics)

@main.route('/mission')
def mission():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/mission.html', title='Mission', posts=posts)

@main.route('/leaders')
def leaders():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/leadership.html', title='Leaders', posts=posts)

@main.route('/contractors')
def contractors():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/contractor_list.html', title='Contractor List', posts=posts)

@main.route('/contacts')
def contacts_page():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/contacts_page.html', title='Contractor List', posts=posts)

@main.route('/reports')
def reports():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/reports.html', title='Reports', posts=posts)

@main.route('/quarterly_report')
def quarterly_report():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/quarterly_report.html', title='Quarterly_report', posts=posts)

@main.route('/organogram')
def organogram():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/organogram.html', title='Organogram', posts=posts) 

@main.route('/completed/periodic', methods=['GET', 'POST'])
def completed_periodic():
    
    form = DateForm()
    posts = Post.query.order_by(Post.id.desc()).all() 

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']
        results = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM completed_proj \
                                    WHERE date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()
        
        return jsonify({'data': render_template('main/completed_periodic_json.html', results=results, form=form)}) 
        
    return render_template('main/completed_periodic.html', title='Completed Periodic Projects', posts=posts, form=form)

@main.route('/ongoing/periodic', methods=['GET', 'POST'])
def ongoing_periodic():
    
    form = DateForm()
    posts = Post.query.order_by(Post.id.desc()).all() 

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']
        results = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()
        
        return jsonify({'data': render_template('main/ongoing_periodic_json.html', results=results, form=form)}) 
        
    return render_template('main/ongoing_periodic.html', title='Ongoing Periodic Projects', posts=posts, form=form)

@main.route('/completed/routine', methods=['GET', 'POST'])
def completed_routine():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/completed_routine.html', title='Completed Routine Projects', posts=posts)

@main.route('/ongoing/routine', methods=['GET', 'POST'])
def ongoing_routine():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/ongoing_routine.html', title='Ongoing Periodic Projects', posts=posts)

@main.route('/planning/periodic', methods=['GET', 'POST'])
def planning_periodic():
    form=DateForm()
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/planning_periodic.html', title='Periodic Projects Under Planning', posts=posts, form=form)

@main.route('/planning/routine', methods=['GET', 'POST'])
def planning_routine():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/planning_routine.html', title='Routine Projects Under Planning', posts=posts)

# Start of Right to information Page
@main.route('/rti_page')
def rti_page():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/rti_page.html', title='RTI Page', posts=posts)

# RTI available_info 
@main.route('/available_info')
def available_info():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('main/available_info.html', title='Available to Information Page', posts=posts)

# RTI application
@main.route('/application')
def application():
    return render_template('/main/application.html', title='Application to Access Information')


# RTI exempt
@main.route('/exempt_info')
def exempt_info():
    return render_template('/main/exempt_info.html', title='Exempt Information')

# Disclosure logs page
@main.route('/disclosure_logs')
def disclosure_logs():
    return render_template('/main/disclosure_logs.html', title='Disclosure Logs')

# Navbar video gallery
@main.route('/video_gallery')
def video_gallery():
    return render_template('/main/video_gallery.html', title='Video Gallery')

# Navbar status report
@main.route('/status_report')
def status_report():
    return render_template('/main/status_report.html', title='Status Report')


# Navbar regional directors
@main.route('/regional_directors')
def regional_directors():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('/main/regional_directors.html', title='Regional Directors', posts=posts)

# Navbar upcoming events
@main.route('/upcoming_event')
def upcoming_event():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('/main/upcoming_event.html', title='Upcoming Event', posts=posts)


@main.route('/xptShare')
def xptShare():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('/main/xptShare.html', title='Xpt Share', posts=posts)


# Start of services route
# Services
@main.route('/lab_test_services')
def lab_test_services():
    return render_template('/main/lab_test_services.html', title='Lab test Services')

# Start of lab_test_services
# route for foundations
@main.route('/foundations')
def foundations():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('/main/foundations.html', title='Foundations', posts=posts)

# route for soil_aggregate_concrete
@main.route('/soil_agg_con')
def soil_agg_con():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('/main/soil_agg_con.html', title='Soil, Aggregate and concrete', posts=posts)

# route for Bitumen
@main.route('/bitumen')
def bitumen():
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('/main/bitumen.html', title='Bitumen & Bituminous Products', posts=posts)

# route for Pavements
@main.route('/pavements')
def pavements():

trial/templates/main/ongoing_periodic_json.html
{% for res in results %} 
    <div class="col-md-6" id="ongoing_proj_sum">
        <label for="" style="font-size: 15px;">Contract Sum</label>
        <input class="form-control" type="text" name="" value="{{ res }}" readonly> 
    </div>
{% endfor %}
        

trial/templates/main/photo-gallery.html
{% extends "includes/layout.html" %}
{% block content %}
<style>
    @media only screen and (max-width:600px) {
        .thumbnails a {
            float: none;
        }

        .thumbnails img {
            height: 202px;
            width: 295px;
        }
    }
</style>

<div class="container">
    <div class="row blog_details_inner" style="margin-top: 50px; margin-left: 2%;">
        <div class="col-md-8" id="tbl_h3" style="margin-top: -2%;">
            <h3 id="table_h3">Photo Gallery</h3>
            <section>
                <div class="thumbnails group">
                    {% for picture in pics %}
                    <a href="{{ url_for('static', filename='gallery/' + picture.image_file) }}" data-lightbox="gallery"
                        data-title="Image {{ loop.index }}" data-alt="image-1">
                        <img src="{{ url_for('static', filename='gallery/' + picture.image_file) }}" alt="image-1">
                    </a>
                    {% endfor %}

                </div>
            </section>
        </div>
        {% include 'includes/sidebar.html' %}
    </div>
</div>
{% endblock content %}

trial/templates/main/road_con_survey.html
{% extends "includes/layout.html" %}
{% block content %}

<style>
    .lab{
        width: 250px; height: 40px; 
        display: block;
        background-color:#b8c3ff;
        color: #333;
        text-align: center;
        padding-top: 16px;
        padding-bottom: 44px;
        border-radius: 10px;
        line-height: 20px;
        font-size: 18px;
        font-family: "Montserrat", sans-serif;
        margin-bottom: 15px;
        margin-right: 20px;
    }

    .lab:hover {
        background-color: #01368c;
        color: #fff;
    }


    .title_head{
        padding-bottom: 10px;
        color: #000;
        font-weight: bold;
    }

    .policy-main {
        margin-bottom: 10px;
        padding: 10px; 
        font-family: 'Montserrat', sans-serif;
        border: 1px dashed #ccc;
    }

    .policy-pdf {
        margin: 20px 0px;
        display: block;
    }

    .fa-file-pdf-o:before {
        content: "\f1c1";
    }

    .policy-pdf-file {
        background-color: #f7f7f7;
        width: 100%;
        display: flex;
        box-sizing: border-box;
        border: 1px solid #e5e5e5;
        vertical-align: bottom;
    }

    .policy-pdf-file a {
        font-size: 20px;
        text-decoration: none;
        flex: 1;
        color: #41aed7;
        padding: 5px;
    }

    .policy-pdf-file span {
        flex: 16;
        font-weight: 400;
        display: inline-block;
        padding: 10px;
        border-right: 1px solid #e5e5e5;
    }

    .divider_bg::before {
        content: "";
        display: block;
        border-bottom: 5px solid #b8c3ff;
        position: absolute;
        left: 0;
        top: -1px;
        width: 83px;
        height: 1px;
        opacity: 1;
        z-index: 100;
    }

    #hr_divider {
        opacity: 1;
        z-index: 1;
    }

    hr {
        box-sizing: content-box;
        height: 0;
        border-top: 1px solid #eee;
        border-color: #e5e5e5;
        background-color: #e5e5e5;
    }

    .divider_bg {
        position: relative;
        overflow: visible;
        margin-top: -10px;
    }

    /* .table{
        margin-top: -12px;
    } */

    @media only screen and (max-width: 600px) {
        .lab {
            width: 335px;
        }

        #periodic {
            flex-direction: column;

        }

        .row{
            margin-right: 0px;
        }

        #no_news{
            text-align: center;
            margin-top: 1rem;
        }

        #table_h3{
            margin-top: 9%;
        }

        /* .table{
            margin-top: -19%;
        } */
        .view_btn1{
            width: 142px;
            height: 44px;
            margin-left: 84px;
        }
       
    }

</style>

<div class="container">
    <div class="row blog_details_inner" style="margin-left: 2%;">
        <h3 id="table_h3">Reports</h3>
        <div id="periodic" style="margin-top: 2%; display: flex;">
            <div>
                <a class="lab" href="{{ url_for('main.reports') }}">Annual Report</a>
                <a class="lab" href="{{ url_for('main.quarterly_report') }}">Quarterly Report</a>
                <a class="lab" href="{{ url_for('main.status_report') }}">Status Report</a>
                <a class="lab" href="{{ url_for('main.road_con_survey') }}">Road Con. And Survey</a>
            </div>
    
            <div style="font-size: 18px; font-family: 'Montserrat', sans-serif; width: 100%;">
                <h5 id="no_news">ROAD CONDITION AND SURVEY REPORT</h5>
            
                <!-- start here  -->
                <div class="road_div" id="periodic">
                    <div>
                        <p style="margin-top: -8%; line-height: 30px; text-align: left; font-size: 17px;">
                            <strong>Comparison of the surveyed trunk road surface network condition 2010-2019</strong>    
                        </p><br>
                        <div style="overflow-x: auto">
                            <table class="table table-bordered" style="margin-left: 10px; text-align: center;">
                                <thead style="font-weight: bolder; line-height: 45px; font-size: 15px;">
                                    <tr>
                                        <td rowspan="2">YEAR</td>
                                        <td colspan="2">GOOD</td>
                                        <td colspan="2">FAIR</td>
                                        <td colspan="2">POOR</td>
                                        <td>TOTAL</td>
                                    </tr>
                                    <tr>
                                        <td>Length (km)</td>
                                        <td>(%)</td>
                                        <td>Length (km)</td>
                                        <td>(%)</td>
                                        <td>Length (km)</td>
                                        <td>(%)</td>
                                        <td>Length (km)</td>
                                    </tr>
                                </thead>
                                <tbody style="font-size: 15px;">
                                    <tr>
                                        <td>2010</td>
                                        <td>3,865</td>
                                        <td>29</td>
                                        <td>5,841</td>
                                        <td>44</td>
                                        <td>3,556</td>
                                        <td>27</td>
                                        <td>13,262</td>
                                    </tr>
                                    <tr>
                                        <td>2011</td>
                                        <td>4,566</td>
                                        <td>34</td>
                                        <td>3758</td>
                                        <td>28</td>
                                        <td>5,019</td>
                                        <td>38</td>
                                        <td>13,343</td>
                                    </tr>
                                    <tr>
                                        <td>2012</td>
                                        <td>6,184</td>
                                        <td>46</td>
                                        <td>4412</td>
                                        <td>33</td>
                                        <td>2,882</td>
                                        <td>21</td>
                                        <td>13,478</td>
                                    </tr>
                                    <tr>
                                        <td>2013</td>
                                        <td>6,490.10</td>
                                        <td>52</td>
                                        <td>4,271.40</td>
                                        <td>34</td>
                                        <td>1,776.50</td>
                                        <td>14</td>
                                        <td>12,538</td>
                                    </tr>
                                    <tr>
                                        <td>2014</td>
                                        <td>7,128.53</td>
                                        <td>52</td>
                                        <td>5,452.09</td>
                                        <td>39</td>
                                        <td>1,256.80</td>
                                        <td>9</td>
                                        <td>13,837</td>
                                    </tr>
                                    <tr>
                                        <td>2015</td>
                                        <td>7,618.50</td>
                                        <td>56.8</td>
                                        <td>4,838.40</td>
                                        <td>36.1</td>
                                        <td>960</td>
                                        <td>7.2</td>
                                        <td>13,416.90</td>
                                    </tr>
                                    <tr>
                                        <td>2016</td>
                                        <td>8,171.92</td>
                                        <td>56</td>
                                        <td>5,428.60</td>
                                        <td>37.2</td>
                                        <td>982.1</td>
                                        <td>6.7</td>
                                        <td>14,582.62</td>
                                    </tr>
                                    <tr>
                                        <td>2017</td>
                                        <td>7,544.00</td>
                                        <td>54</td>
                                        <td>4,874.20</td>
                                        <td>35</td>
                                        <td>1,582.40</td>
                                        <td>11</td>
                                        <td>14,000.60</td>
                                    </tr>
                                    <tr>
                                        <td>2018</td>
                                        <td>6,248.50</td>
                                        <td>45</td>
                                        <td>5,558.20</td>
                                        <td>40</td>
                                        <td>2,060.60</td>
                                        <td>15</td>
                                        <td>13,867.30</td>
                                    </tr>
                                    <tr>
                                        <td>2019</td>
                                        <td>4,548.20</td>
                                        <td>32</td>
                                        <td>6,954.50</td>
                                        <td>49</td>
                                        <td>2,647.50</td>
                                        <td>19</td>
                                        <td>14,150.20</td>
                                    </tr>
                                </tbody>
                            </table><br>
                        </div>    
                    </div>
                    <section style="margin-top: 5%;">
                        <div class="col-sm-4">
                            <table>
                                <tbody>
                                    <tr>
                                        <td><a class="view_btn1" href="{{ url_for('main.report_2018') }}">2018 Report</a></td> 
                                    </tr>
                                </tbody>
                            </table>
                        </div> 
                        <div class="col-sm-4">
                            <table>
                                <tbody>
                                    <tr>
                                        <td><a class="view_btn1" href="{{ url_for('main.report_2019') }}">2019 report</a></td> 
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col-sm-4">
                            <table>
                                <tbody>
                                    <tr>
                                        <td><a class="view_btn1" href="{{ url_for('main.proj_funding') }}">2020 Report</a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div> 
                    </section>
                </div>

                <!-- end here -->

            </div>
        </div>
        
        
        
    </div>
</div>
{% endblock content %}