trial/blogs/routes.py
from flask import render_template, redirect, request, Blueprint
from trial import db
from trial.models import Post, Comment
from flask_simple_captcha import CAPTCHA

blogs = Blueprint('blogs', __name__)
  
#Route for Latest news Page
@blogs.route('/blog') 
def blog():
    #Get the page you want from a query parameter
    page = request.args.get('page', 1, type=int)
    posts_pag = Post.query.order_by(Post.id.desc()).paginate(page=page, per_page=2, error_out=True)
    posts = Post.query.order_by(Post.id.desc()).all()
    return render_template('blogs/blog.html', title='Latest News', posts=posts, posts_pag=posts_pag) 

#Route for Latest news Page
@blogs.route('/blog_post/<int:post_id>/<string:slug>', methods=['GET', 'POST']) 
def blog_post(post_id, slug):
    
    # if request.method == 'GET':
    #     captcha = CAPTCHA.create()
    #     render_template('blogs/blog_post.html', captcha=captcha)
    # if request.method == 'POST':
    #     c_hash = request.form.get('captcha-hash')
    #     c_text = request.form.get('captcha-text')
    #     if CAPTCHA.verify(c_text, c_hash):
    #         return 'success'
    #     else:
    #         return 'failed captcha'
    
    single_post = Post.query.get_or_404(post_id)
    posts = Post.query.order_by(Post.id.desc()).all()
    # comments = Comment.query.filter_by(post_id=single_post.id).all()   
    single_post.views += 1
    db.session.commit()  
 
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email') 
        message = request.form.get('message')

        comment = Comment(name=name, email=email, message=message, post_id=single_post.id) 
        db.session.add(comment)
        
        db.session.commit()
        return redirect(request.url)

    return render_template('blogs/blog_post.html', title='Latest News', single_post=single_post, posts=posts) #comments=comments)

trial/ongoing_proj/routes.py
from flask import render_template, redirect, request, Blueprint, jsonify
from trial import db
from datetime import datetime
from trial.models import Post, OngoingProj
from trial.projects.forms import DateForm
import re


ongoing_proj = Blueprint('ongoing_proj', __name__)


@ongoing_proj.route('/ongoing/periodic/rehabilitation', methods=['GET', 'POST'])
def rehabilitation():
    rehab_list = OngoingProj.query.filter_by(category="Rehabilitation")
    posts = Post.query.order_by(Post.id.desc()).all()

    if request.method == "POST":
        start_date = datetime.strptime(request.form['start_date'], "%Y-%m-%d").strftime("%Y-%m-%d") 
        end_date = datetime.strptime(request.form['end_date'], "%Y-%m-%d").strftime("%Y-%m-%d")  

        q = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE category = 'Rehabilitation'  and date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()

        return jsonify({'data': render_template('projects/ongoing/rehab_json.html', q=q)})

    return render_template('projects/ongoing/rehabilitation.html', title='Rehabilitation', rehab_list=rehab_list, posts=posts)

@ongoing_proj.route('/ongoing/periodic/resealing', methods=['GET', 'POST']) 
def resealing():
    
    reseal_list = OngoingProj.query.filter_by(category="Resealing")
    posts = Post.query.order_by(Post.id.desc()).all()

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']  
        
        q = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE category = 'Resealing'  and date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()

        return jsonify({'data': render_template('projects/ongoing/reseal_json.html', q=q)})

    return render_template('projects/ongoing/resealing.html', title='Resealing', reseal_list=reseal_list, posts=posts)
@ongoing_proj.route('/ongoing/periodic/reconstruction', methods=['GET', 'POST']) 
def reconstruction():
    
    reconstruct_list = OngoingProj.query.filter_by(category="Reconstruction")
    posts = Post.query.order_by(Post.id.desc()).all()

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']  
        
        q = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE category = 'Reconstruction'  and date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()

        return jsonify({'data': render_template('projects/ongoing/reconstruct_json.html', q=q)})

    return render_template('projects/ongoing/reconstruction.html', title='Reconstruction', reconstruct_list=reconstruct_list, posts=posts)

@ongoing_proj.route('/ongoing/periodic/resurfacing', methods=['GET', 'POST']) 
def resurfacing():
    
    resurface_list = OngoingProj.query.filter_by(category="Resurfacing")
    posts = Post.query.order_by(Post.id.desc()).all()

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']  
        
        q = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE category = 'Resurfacing'  and date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()

        return jsonify({'data': render_template('projects/ongoing/resurface_json.html', q=q)})

    return render_template('projects/ongoing/resurfacing.html', title='Resurfacing', resurface_list=resurface_list, posts=posts)

@ongoing_proj.route('/ongoing/periodic/repairs_asphaltic', methods=['GET', 'POST']) 
def repairs_asphaltic():
    
    repairs_list = OngoingProj.query.filter_by(category="Repairs & Asphaltic")
    posts = Post.query.order_by(Post.id.desc()).all()

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']  
        
        q = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE category = 'Repairs & Asphaltic'  and date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()

        return jsonify({'data': render_template('projects/ongoing/repairs_json.html', q=q)})

    return render_template('projects/ongoing/repairs_aphaltic.html', title='Repairs & Asphaltic', repairs_list=repairs_list, posts=posts)

@ongoing_proj.route('/ongoing/periodic/preconstruction', methods=['GET', 'POST']) 
def preconstruct():
    
    precons_list = OngoingProj.query.filter_by(category="Pre-Construction")
    posts = Post.query.order_by(Post.id.desc()).all()

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']  
        
        q = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE category = 'Pre-Construction'  and date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()

        return jsonify({'data': render_template('projects/ongoing/precons_json.html', q=q)})

    return render_template('projects/ongoing/preconstruction.html', title='Preconstruction', precons_list=precons_list, posts=posts)

@ongoing_proj.route('/ongoing/periodic/asphalticoverlay', methods=['GET', 'POST']) 
def asphalticoverlay():
    
    overlay_list = OngoingProj.query.filter_by(category="Asphaltic Overlay")
    posts = Post.query.order_by(Post.id.desc()).all()

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']  
        
        q = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE category = 'Asphaltic Overlay'  and date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()

        return jsonify({'data': render_template('projects/ongoing/asphaltic_json.html', q=q)})

    return render_template('projects/ongoing/asphaltic_overlay.html', title='Asphaltic Overlay', overlay_list=overlay_list, posts=posts)

@ongoing_proj.route('/ongoing/periodic/upgrading', methods=['GET', 'POST']) 
def upgrading():
    
    upgrade_list = OngoingProj.query.filter_by(category="Upgrading")
    posts = Post.query.order_by(Post.id.desc()).all()

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']  
        
        q = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE category = 'Upgrading'  and date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()

        return jsonify({'data': render_template('projects/ongoing/upgrade_json.html', q=q)})

    return render_template('projects/ongoing/upgrading.html', title='Upgrading', upgrade_list=upgrade_list, posts=posts)

@ongoing_proj.route('/ongoing/periodic/decongestion', methods=['GET', 'POST']) 
def decongestion():
    
    deconges_list = OngoingProj.query.filter_by(category="Decongestion")
    posts = Post.query.order_by(Post.id.desc()).all()

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']  
        
        q = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE category = 'Decongestion'  and date_commenced >= %s  and date_completed<= %s) t1", \
                                    (start_date, end_date)).first()

        return jsonify({'data': render_template('projects/ongoing/decongestion_json.html', q=q)})

    return render_template('projects/ongoing/decongestion.html', title='Decongestion', deconges_list=deconges_list, posts=posts)

@ongoing_proj.route('/ongoing/periodic/supply_inst', methods=['GET', 'POST']) 
def supply(): 
    
    supply_list = OngoingProj.query.filter_by(category="Supply & Installation of Materials")
    posts = Post.query.order_by(Post.id.desc()).all()

    if request.method == "POST":
        start_date = request.form['start_date']
        end_date = request.form['end_date']  
        
        q = db.engine.execute("SELECT FORMAT((t1.col_total), 2)   As col_total \
                                    FROM (SELECT IFNULL(SUM(amt_to_date),0) As col_total FROM ongoing_proj \
                                    WHERE category = 'Supply & Installation of Materials'  and date_commenced >= %s  and date_completed<= %s) t1", \

trial/templates/includes/ongoing_scripts.html
<!--Ajax script for Ongoing Rehabilitation project's sum-->
<script>
    $(document).ready(function(){  
        $('#ongoing_rehab_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.rehabilitation') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_rehab_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing Asphaltic Overlay project's sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_asphaltic_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.asphalticoverlay') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_asphaltic_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing Bituminous Surfacing sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_bitum_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.bituminous') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_bitum_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing Construction Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_const_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.construction') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_const_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing Construction Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_decongest_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.decongestion') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_decongest_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing Drainage Structure Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_drainage_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.drainage_struct') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_drainage_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing Grading Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_grading_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.grading') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_grading_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing Other Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_otherproj_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.other_proj') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_otherproj_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing Partial Reconstruction Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_part_reconst_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.part_reconst') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_part_reconst_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing  Pre-Construction Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_precons_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.preconstruct') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_precons_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing  Regravelling Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_regrav_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.regravelling') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_regrav_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing  Repairs & Asphaltic Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_repairs_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.repairs_asphaltic') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_repairs_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing  Resealing Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_reseal_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.resealing') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_reseal_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing  Resurface Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_resurface_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.resurfacing') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_resurface_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing  Supply Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_supply_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.supply') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_supply_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing  Surface Dressing Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_surf_dress_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.surface_dressing') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_surf_dress_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>
<!--Ajax script for Ongoing Upgrading Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_upgrade_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.upgrading') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_upgrade_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        }); 
    });
</script>
<!--Ajax script for Ongoing Reconstruction Projects' sum-->
<script>
    $(document).ready(function(){
        $('#ongoing_reconstruct_sub').on('click', function(event){

            var start_date = $('#start_date').val();
            var end_date = $('#end_date').val();

            $.ajax({
                type : "POST",
                url : "{{ url_for('ongoing_proj.reconstruction') }}",
                dataType: "json",
                data : {
                    start_date: start_date, end_date : end_date
                },
                success: function(data){
                    $('#ongoing_reconstruct_sum').replaceWith(data.data) 
                }
            });
            event.preventDefault();
        });
    });
</script>

trial/templates/includes/sidebar.html
<div class="col-md-4">
    <div class="sidebar_area" style="margin-top: 11px;">
        <aside class="right_widget r_post_widget">
            <div class="r_w_title">
                <h3 style="font-weight: bolder;">Trending Post</h3>   
            </div>
            {% if posts %}
            <div class="r_post_inner">
                {% for post in posts[0:3] %}
                <div class="r_post_item">
                    <img src="{{ url_for('static', filename='blog_images/' + post.image) }}" style="width: 246px; height: 123px;" alt="">
                    <a href="{{ url_for('blogs.blog_post', post_id=post.id, slug=post.slug) }}"><p>{{ post.title | truncate(80, True) }}</p></a>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div>
                No Trending Posts
            </div>
            {% endif %}
        </aside>
        <aside class="right_widget r_social_widget">
            <div class="r_w_title">
                <h3>we are social</h3>
            </div>
            <ul>
                <li><a href="https://www.twitter.com/highwaysghana/" target="_blank"><i class="fa fa-twitter"></i></a></li>
                <li><a href="https://www.linkedin.com/company/highwaysghana/" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="https://www.youtube.com/channel/UCiW23XAZoBFwgTDVRD_om7g" target="_blank"><i class="fa fa-youtube"></i></a></li>
                <li><a href="https://www.instagram.com/highwaysghana/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                <!-- <li><a href="#" target="_blank"><i class="fa fa-pinterest"></i></a></li> -->
                <li><a href="https://www.facebook.com/highwaysghana/" target="_blank"><i class="fa fa-facebook"></i></a></li>

            </ul>
        </aside>
        <aside class="right_widget r_twitter_widget">
            <div class="r_w_title">
                <h3>twitter feed</h3>
            </div>
            <div class="tweets_feed">
                <a class="twitter-timeline" data-width="300" data-height="300" href="https://www.twitter.com/highwaysghana?ref_src=twsrc%5Etfw">Tweets by Ghana_Highway</a>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
        </aside>
    </div>
</div>